# Setup
title:               Sean's Blog
tagline:             'A simple site to check out some of my work'
description:         'Check out my <a href="https://github.com/seanledesma" target="_blank">Github</a> or find me on twitter at <a href="https://x.com/sledesco" target="_blank">@sledesco</a>.'
url:                 https://seanledesma.dev
baseurl:             ''
paginate:            5
paginate_path:       "/blog/page:num/"
permalink:           pretty

# About/contact
author:
  name:              Sean Ledesma
  url:               https://x.com/sledesco
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y



