name: Jekyll Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Pulls the code from your repo

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # Sets Ruby version to use for Jekyll

      - name: Install dependencies
        run: bundle install  # Installs Jekyll and any other gems

      - name: Build site
        run: bundle exec jekyll build  # Builds the Jekyll site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Deploys the output in _site

